sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            Posts:
                label: 'Posts'
                icon: '<i class="fa fa-newspaper"></i>'
                items:
                    - admin: admin.article
                    - route: admin_article_stats
                      label: 'Graph'
            Users:
                label: 'Users'
                icon: '<i class="fa fa-user"></i>'
                items:
                    - route: admin_app_sonatauseruser_list
                      label: 'Users'
    security:
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

    options:
        form_type: standard
    templates:
        form_theme: ['@SonataAdmin/Form/form_admin_fields.html.twig']

sonata_user:
    resetting:
        email:
            address: 'no-reply@example.com'
            sender_name: 'No Reply'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
